version: '2'
services:
  shoppingstore-app:
    image: shoppingstore
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://shoppingstore-mysql:3306/shoppingstore?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8040:8040
  shoppingstore-mysql:
    extends:
      file: mysql.yml
      service: shoppingstore-mysql
